parameters:
    pim_enrich.imagine.local_dir_resolver.class:  Pim\Bundle\EnrichBundle\Imagine\Cache\Resolver\LocalDirResolver
    pim_enrich.event_listener.user_context.class: Pim\Bundle\EnrichBundle\EventListener\UserContextListener
    pim_enrich.provider.colors.class:             Pim\Bundle\EnrichBundle\Provider\ColorsProvider
    pim_enrich.twig.locale_extension.class:       Pim\Bundle\EnrichBundle\Twig\LocaleExtension
    pim_enrich.twig.category_extension.class:     Pim\Bundle\EnrichBundle\Twig\CategoryExtension
    pim_enrich.twig.channel_extension.class:      Pim\Bundle\EnrichBundle\Twig\ChannelExtension
    pim_enrich.twig.attribute_extension.class:    Pim\Bundle\EnrichBundle\Twig\AttributeExtension
    pim_enrich.twig.object_class_extension.class: Pim\Bundle\EnrichBundle\Twig\ObjectClassExtension
    pim_enrich.twig.version_extension.class:      Pim\Bundle\EnrichBundle\Twig\VersionExtension
    pim_enrich.event_listener.request.class:      Pim\Bundle\EnrichBundle\EventListener\RequestListener

services:
    # Media management
    pim_enrich.imagine.local_dir_resolver:
        class: %pim_enrich.imagine.local_dir_resolver.class%
        parent: liip_imagine.cache.resolver.web_path
        arguments:
            - %kernel.cache_dir%/media
        tags:
            - { name: liip_imagine.cache.resolver, resolver: local_dir }

    # Color management
    pim_enrich.provider.colors:
        class: %pim_enrich.provider.colors.class%
        arguments:
            - %pim_enrich.colors%

    # Twig extensions
    pim_enrich.twig.locale_extension:
        class: %pim_enrich.twig.locale_extension.class%
        arguments:
            - '@pim_catalog.helper.locale'
        tags:
            - { name: twig.extension }

    pim_enrich.twig.category_extension:
        class: %pim_enrich.twig.category_extension.class%
        arguments:
            - '@pim_catalog.manager.product_category'
        tags:
            - { name: twig.extension }

    pim_enrich.twig.channel_extension:
        class: %pim_enrich.twig.channel_extension.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_enrich.provider.colors'
        tags:
            - { name: twig.extension }

    pim_enrich.twig.attribute_extension:
        class: %pim_enrich.twig.attribute_extension.class%
        arguments:
            - %pim_enrich.attribute_icons%
        tags:
            - { name: twig.extension }

    pim_enrich.twig.object_class_extension:
        class: %pim_enrich.twig.object_class_extension.class%
        tags:
            - { name: twig.extension }

    pim_enrich.twig.version_extension:
        class: %pim_enrich.twig.version_extension.class%
        tags:
            - { name: twig.extension }

    pim_enrich.event_listener.request:
        class: %pim_enrich.event_listener.request.class%
        tags:
            - { name: kernel.event_subscriber }

    # User context listener
    stof_doctrine_extensions.event_listener.locale:
        class: %pim_enrich.event_listener.user_context.class%
        arguments:
            - '@security.context'
            - '@pim_translation.listener.add_locale'
            - '@pim_catalog.context.catalog'
            - '@pim_user.context.user'
        tags:
            - { name: kernel.event_subscriber }
